---
- name: Stop specified Alpine containers
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    container_names:
      - alpine1
      - alpine2
      - alpine3

  tasks:
    - name: Stop Alpine containers
      community.docker.docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ container_names }}"
