---
- name: Stop all running Alpine containers
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Get list of running Alpine containers
      community.docker.docker_container_info:
        name: "{{ item }}"
      loop: "{{ query('community.docker.docker_containers', filters={'ancestor': 'alpine:latest'}) }}"
      register: alpine_containers

    - name: Stop Alpine containers
      community.docker.docker_container:
        name: "{{ item.item }}"
        state: stopped
      loop: "{{ alpine_containers.results }}"
